# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 700481dd6f78f328ba10d32a2e20f99fd184e23b757ec18c41c4627aee14a4190cae3938e5cf26cbd8769ba2a1fea2f3f9f3d4576c984ced50e8e41c1bc9d552

test:
  secret_key_base: 57c720caba503d03218570ea37918e8f0aabae783e2e5c910aa6404737d787a68a4c98ecd5e0dfda061eb5b51a58dea78827b61435695613d736007ec3649248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
